In [1]:
import numpy as np

In [9]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.linspace(0,9,4, dtype=np.int16)

array([0, 3, 6, 9], dtype=int16)

In [21]:
np.full((2,3),7).ndim

2

In [18]:
np.eye(3,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])